version: "3.8"
services:
  whoami:
    image: traefik/whoami:v1.10
    command:
      - --verbose 
  debian:
    image: debian:bookworm
    command:
      - bash
      - -c
      - apt update && apt install -y curl && while true; do sleep 1; curl whoami/api; done
  lolcat:
    image: ubuntu:22.04
    command:
      - bash
      - -c
      - apt update && apt install -y lolcat && while true; do sleep 1; date | /usr/games/lolcat; done
    tty: true
    environment: 
      TERM: xterm-256color
