name: Rust

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Build
      run: cargo build --verbose
    - name: Format
      run : cargo fmt --verbose
    - name: Clippy
      run: cargo clippy
    - name: Run tests
      run: cargo test --verbose
  cross-build:
    needs: build
    strategy:
      matrix:
        target:
          - aarch64-unknown-linux-gnu
          - aarch64-apple-darwin
          - x86_64-unknown-linux-gnu
          - x86_64-apple-darwin
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Install Rust
        run: rustup update stable
      - name: Install toolchains
        run: rustup target add ${{ matrix.target }}
      - name: cross build
        run: cargo build --target ${{ matrix.target }}
